apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    database: homeassistant
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      dbName: homeassistant
      httpMode: GET

