name: "Water Data Importer"
description: "Upload JSON water logs to InfluxDB"
version: "1.0.0"
slug: "water_importer"
arch:
  - aarch64
  - amd64
ingress: true
panel_icon: "mdi:water"
startup: application
options:
  influx_host: "a0d7b954-influxdb"
  influx_port: 8086
  influx_db: "homeassistant"
schema:
  influx_host: str
  influx_port: int
  influx_db: str
