name: "Water Data Importer"
description: "Flask app to import water consumption data to InfluxDB"
slug: "water-importer"
version: "1.0.4"
arch:
  - amd64
  - aarch64
init: false
boot: auto
startup: services

ingress: true
ingress_port: 5000
panel_icon: "mdi:water-pump"

ports:
  5000/tcp: 5000

options:
  influx_host: "homeassistant.local"
  influx_port: 8086
  influx_db: "homeassistant"
  influx_user: "homeassistant"
  influx_password: "homeassistant"
  flask_port: 5000

schema:
  influx_host: str
  influx_port: int
  influx_db: str
  influx_user: str
  influx_password: str
  flask_port: int

environment:
  PYTHONUNBUFFERED: "1"